apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: test
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 20Gi
    limits.cpu: "1"
    limits.memory: 30Gi
