kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-manager
subjects:
- kind: User
  name: oidc:rjain@lab.int
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: oidc:people
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
